"""Add likes column to Page model

Revision ID: 070cd2e026ae
Revises: 
Create Date: 2025-05-18 05:17:21.810721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070cd2e026ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
